apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: uzieljr/my-adminer:01
          ports:
            - containerPort: 8080
          env:
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: 900MB
            - name: ADMINER_DESIGN
              value: Hydra